# Generated by Django 4.0.2 on 2022-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('stereotype', models.TextField()),
                ('reality', models.TextField()),
                ('day_in_life', models.TextField()),
                ('income', models.IntegerField()),
                ('education', models.TextField()),
                ('others', models.TextField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
